### ISSUE TITLE
BrisJS website

### ISSUE THREAD

**Issue by garrows** [BrisJS/BrisJS.github.io#1]
Hey @nigelr @kevdesign @MauriceButler,

During last nights meetup after I saw you had brisjs.com just redirecting to the meetup site, I thought you could use a proper site so I made you one during the talks. 
http://brisjs.github.io/

The wording/content needs some work though but its enough to get you guys started if you want to use it. Also if you prefer to keep brisjs.com pointing directly to the meetup, that is fine with me. 

Cheers

**Comment by MauriceButler** [comment]
Thanks mate, looks good.

**Comment by garrows** [comment]
Been published to https://bris.js.org with an update from the talented mr @AshKyd
