### ISSUE TITLE
Crash in latest update

### ISSUE THREAD

**Issue by garrows** [BrisJS/BrisJS.github.io#11]
Looks like its in the contacts. 

![image](https://cloud.githubusercontent.com/assets/205256/25431830/8db85ec8-2ac5-11e7-996d-8db4fd1c9629.png)

**Comment by garrows** [comment]
Sorry 😢  still getting the same thing @AshKyd

**Comment by AshKyd** [comment]
Wait, do I need to build app.min.js before committing?

**Comment by garrows** [comment]
Yes. github doesn't run the build step.

**Comment by AshKyd** [comment]
Gotcha. If possibly, we should move to [Netlify](https://netlify.com) or something that will do it for us, as it does the build step and means we can make changes from GitHub.
