### ISSUE TITLE
Implement our own CORS proxy for Meetup Issues feed

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/BrisJS.github.io#5]
At the moment we're using https://crossorigin.me/ which is slow and not meant to be used in production. Unless anyone has a better idea, I can set one up on my server and open it up for general access.

**Comment by iamkevinv** [comment]
It's a good idea. I think we will have to start moving everything to brisJS owned and paid for servers/hosting/etc. Just to ensure continuity of everything. But for now i am grateful and honoured by your contributions.
