### ISSUE TITLE
Add past talks

### ISSUE THREAD

**Issue by AnnaGerber** [BrisJS/BrisJS.github.io#9]
Please add some info to make it easier to find resources that have been attached to closed issues for past talks and the videos too (would be nice to have a list of previous talks like the proposed talks)

**Comment by iamkevinv** [comment]
A candidate search would be:
https://github.com/BrisJS/meetups/issues?q=is%3Aissue+label%3A%22Resources+Shared%22+is%3Aclosed

**Comment by AshKyd** [comment]
This is a good idea. I have crawled past meetups and started a spreadsheet, I think this will be a better way to get deep metadatas. Will export it to JSON and include it in the repo when we've got all the historical data.

Feel free to pitch in if you'd like: https://docs.google.com/spreadsheets/d/1paafwoek3xLd0-FtcH6CyM4qBL3TwoHObHL9rcg9MuU/edit?usp=sharing

**Comment by AshKyd** [comment]
The older data is pretty spotty, so there's some missing metadata in some of the original events. The new data is looking fantastic though, I've correlated the Youtube vids, just gotta pull in the slides/resources and I reckon we'll be able to do up a pretty swanky archive.
